<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="suite" duration-ms="45192" started-at="2020-04-14T08:49:43Z" finished-at="2020-04-14T08:50:28Z">
    <groups>
    </groups>
    <test name="RTU" duration-ms="45129" started-at="2020-04-14T08:49:43Z" finished-at="2020-04-14T08:50:28Z">
      <class name="com.dywl.iot.testCase.RTU.RTU_Update_Page">
        <test-method status="FAIL" signature="RTUCalibration()[pri:0, instance:com.dywl.iot.testCase.RTU.RTU_Update_Page@769e7ee8]" name="RTUCalibration" duration-ms="7848" started-at="2020-04-14T16:49:58Z" finished-at="2020-04-14T16:50:06Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.dywl.iot.base.BaseTest.assertPartialTextPresent(BaseTest.java:475)
	at com.dywl.iot.base.BaseTest.assertPartialTextPresent(BaseTest.java:485)
	at com.dywl.iot.testCase.RTU.RTU_Update_Page.RTUCalibration(RTU_Update_Page.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:968)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1149)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RTUCalibration -->
        <test-method status="FAIL" signature="RTUCalibration()[pri:0, instance:com.dywl.iot.testCase.RTU.RTU_Update_Page@769e7ee8]" name="RTUCalibration" duration-ms="7194" started-at="2020-04-14T16:50:06Z" finished-at="2020-04-14T16:50:13Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.dywl.iot.base.BaseTest.assertPartialTextPresent(BaseTest.java:475)
	at com.dywl.iot.base.BaseTest.assertPartialTextPresent(BaseTest.java:485)
	at com.dywl.iot.testCase.RTU.RTU_Update_Page.RTUCalibration(RTU_Update_Page.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:968)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1149)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RTUCalibration -->
        <test-method status="PASS" signature="RTUFastCalibration()[pri:0, instance:com.dywl.iot.testCase.RTU.RTU_Update_Page@769e7ee8]" name="RTUFastCalibration" duration-ms="15057" started-at="2020-04-14T16:50:13Z" finished-at="2020-04-14T16:50:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RTUFastCalibration -->
      </class> <!-- com.dywl.iot.testCase.RTU.RTU_Update_Page -->
    </test> <!-- RTU -->
    <test name="Lamp" duration-ms="2" started-at="2020-04-14T08:50:28Z" finished-at="2020-04-14T08:50:28Z">
      <class name="com.dywl.iot.testCase.RTU.RTU_Update_Page">
        <test-method status="PASS" signature="case01(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.dywl.iot.testCase.RTU.RTU_Update_Page@769e7ee8]" name="case01" is-config="true" duration-ms="30294" started-at="2020-04-14T16:49:13Z" finished-at="2020-04-14T16:49:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[2.X]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[src/test/resources/2.53.1/chromedriver.exe]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- case01 -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.dywl.iot.testCase.RTU.RTU_Update_Page@769e7ee8]" name="afterSuite" is-config="true" duration-ms="5004" started-at="2020-04-14T16:50:29Z" finished-at="2020-04-14T16:50:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.dywl.iot.testCase.RTU.RTU_Update_Page -->
    </test> <!-- Lamp -->
  </suite> <!-- suite -->
</testng-results>
